CREATE DATABASE TT_QLTV
GO

USE TT_QLTV
GO
CREATE TABLE SACH (
     MASACH INT IDENTITY(1,1) NOT NULL,
	TENSACH NVARCHAR(50),
	 GIATRI NVARCHAR(20)
)
Go
go
CREATE TABLE NHANVIEN (
    MANV INT IDENTITY(1,1) NOT NULL,
	HOTEN NVARCHAR(40),
	NS DATE,
	GT NVARCHAR(4)
)
Go
go
CREATE TABLE NGUOIMUON(
    MANM INT IDENTITY(1,1) NOT NULL,
	HOTEN NVARCHAR(40),
	NS DATE,
	GT NVARCHAR(4),
	DC NVARCHAR(100),
	SDT NCHAR(15)
	)
GO
CREATE TABLE MUONSACH(
   MAMUON INT IDENTITY(1,1) NOT NULL,
   MANV INT,
   MANM INT,
   MASACH INT,
   THOIGIAN DATE,
   DATRAHAYCHUA NVARCHAR(30)
   )
GO
 
CREATE TABLE THELOAI(
   MATHELOAI INT IDENTITY(1,1) NOT NULL,
   TENTHELOAI NVARCHAR(100)
   )
GO
CREATE TABLE TACGIA(
   MATG INT IDENTITY(1,1) NOT NULL,
   TENTG NVARCHAR(40)
   )
GO
CREATE TABLE PHANLOAI(
   MAPL INT IDENTITY(1,1) NOT NULL,
   MASACH INT,
   MATHELOAI INT
   )
GO
CREATE TABLE SANGTAC(
   MASANGTAC INT IDENTITY(1,1) NOT NULL,
   MATG INT,
   MASACH INT
   )
GO
ALTER TABLE dbo.SACH ADD CONSTRAINT PK_MASACH  PRIMARY KEY(MASACH)
ALTER TABLE dbo.NHANVIEN ADD CONSTRAINT PK_MANV  PRIMARY KEY(MANV)
ALTER TABLE dbo.NGUOIMUON ADD CONSTRAINT PK_MANM  PRIMARY KEY(MANM)
ALTER TABLE dbo.MUONSACH ADD CONSTRAINT PK_MAMUON  PRIMARY KEY(MAMUON)
ALTER TABLE dbo.THELOAI ADD CONSTRAINT PK_MATHELOAI  PRIMARY KEY(MATHELOAI)
ALTER TABLE dbo.TACGIA ADD CONSTRAINT PK_MATG  PRIMARY KEY(MATG)
ALTER TABLE dbo.SANGTAC ADD CONSTRAINT PK_MASANGTAC  PRIMARY KEY(MASANGTAC) 
ALTER TABLE dbo.PHANLOAI ADD CONSTRAINT PK_MAPL  PRIMARY KEY(MAPL)
ALTER TABLE dbo.SANGTAC ADD CONSTRAINT FK_MASACH_ST_SA FOREIGN KEY(MASACH) REFERENCES dbo.SACH(MASACH)
ALTER TABLE dbo.SANGTAC ADD CONSTRAINT FK_MATG_ST_TG FOREIGN KEY(MATG) REFERENCES dbo.TACGIA(MATG)
ALTER TABLE dbo.PHANLOAI ADD CONSTRAINT FK_MASACH_PL_SA FOREIGN KEY(MASACH) REFERENCES dbo.SACH(MASACH)
ALTER TABLE dbo.PHANLOAI ADD CONSTRAINT FK_MATHELOAI_PL_TL FOREIGN KEY(MATHELOAI) REFERENCES dbo.THELOAI(MATHELOAI)
ALTER TABLE dbo.MUONSACH ADD CONSTRAINT FK_MASACH_TS_SA FOREIGN KEY(MASACH) REFERENCES dbo.SACH(MASACH)
ALTER TABLE dbo.MUONSACH ADD CONSTRAINT FK_MANV_MS_NV FOREIGN KEY(MANV) REFERENCES dbo.NHANVIEN(MANV)
ALTER TABLE dbo.MUONSACH ADD CONSTRAINT FK_MANM_MS_NM FOREIGN KEY(MANM) REFERENCES dbo.NGUOIMUON(MANM)

GO
------------SÁCH-----------
INSERT INTO SACH(TENSACH , GIATRI)
VALUES(N'Để trở thành code điên','120000')
GO
INSERT INTO SACH(TENSACH , GIATRI)
VALUES(N'Mười vạn câu hỏi vì sao','300000')
GO

create PROC USP_GETSACH 
AS 
begin
SELECT MASACH,TENSACH,GIATRI
FROM SACH
end
exec USP_GETSACH
GO
--TẠO PROC THÊM
CREATE PROC USP_INSERTSACH
	@TENSACH NVARCHAR(50),
	@GIATRI NVARCHAR(20)
AS
BEGIN
	INSERT INTO SACH(TENSACH, GIATRI)
	VALUES(@TENSACH, @GIATRI)
END
GO
 
--TẠO PROC SỬA:
CREATE PROC USP_UPDATESACH
	@MASACH INT,
	@TENSACH NVARCHAR(50),
	@GIATRI NVARCHAR(20)
AS
BEGIN 
	UPDATE SACH
	SET TENSACH = @TENSACH, GIATRI = @GIATRI
	WHERE MASACH = @MASACH
END
GO

--TẠO PROC XOÁ
CREATE PROC USP_DELETESACH
	@MASACH INT
AS
BEGIN
	DELETE SACH 
	WHERE MASACH = @MASACH
END
GO

--TẠO PROC TÌM KIẾM
CREATE PROCEDURE USP_SEARCHSACH
	@SEARCHVALUE NVARCHAR(50)
AS
BEGIN
	SELECT MASACH,TENSACH,GIATRI
	FROM SACH 
	WHERE (MASACH LIKE N'%' + @SEARCHVALUE + '%') 
		OR (TENSACH LIKE N'%' + @SEARCHVALUE + '%') 
		OR (GIATRI LIKE N'%' + @SEARCHVALUE + '%') 	
END
GO

    -------------------------------------SANG TAC-----------------------
	---GETALL---
	CREATE PROC USP_SANGTAC_GETDSST
	AS
	    SELECT *FROM SANGTAC
	GO

	 ---INSERT----------------
	 CREATE PROC USP_SANGTAC_INSERT
	            @maTG int,
				@maSach int
	 AS
	 BEGIN
	    INSERT [dbo].[SANGTAC]( MATG, MASACH)
		VALUES (@maTG,@maSach)
	 END
	 GO


	 ------UPDATE-----------------
	 CREATE PROC USP_SANGTAC_UPDATE
	       @maST int,
		   @maTG int,
		   @maSach int
	AS
	BEGIN
	 UPDATE [dbo].[SANGTAC]
	 SET MATG = @maTG ,MASACH = @maSach
	 WHERE MASANGTAC = @maST
	END
	GO

	----------------DELETE------------------
	CREATE PROC USP_SANGTAC_DELETE
	     @maST INT

	AS
	BEGIN
	   DELETE [dbo].[SANGTAC]
	   WHERE MASANGTAC = @maST
	END
	GO

	------------SEARCH--------------------
	CREATE PROC USP_SANGTAC_SEARCH
	    @SEARCH NVARCHAR(100)
	AS
	BEGIN
	   SELECT MASANGTAC, MATG, MASACH
		FROM [dbo].[SANGTAC]
		WHERE (MASANGTAC LIKE N'%' + @SEARCH +'%')
		OR (MATG LIKE N'%' + @SEARCH + '%')
		OR (MASACH LIKE N'%' + @SEARCH + '%')
	END
	GO


	
	 INSERT [dbo].[TACGIA]( TENTG)
	 VALUES (N'Nguyễn Văn A')
	 INSERT [dbo].[TACGIA]( TENTG)
	 VALUES (N'Hoàng Văn X')
	 GO


	 [dbo].[USP_INSERTSACH] N'Giáo Dục Thể Chất', '100000'
	 GO
	 [dbo].[USP_INSERTSACH] N'Giải Tích 1', '200000'
	 GO
	 SELECT *FROM [dbo].[TACGIA]
	 SELECT *FROM [dbo].[SACH]
	 select *from [dbo].[SANGTAC]
<<<<<<< HEAD
	 ----Nhân Viên-----
CREATE PROC USP_GETNV
AS 
begin
SELECT MANV,HOTEN,NS,GT
FROM NHANVIEN
end
exec USP_GETNV
GO
--TẠO PROC THÊM
CREATE PROC USP_INSERTNV
	@HOTEN NVARCHAR(40),
	@NS DATE,
	@GT NVARCHAR(4)
AS
BEGIN
	INSERT INTO NHANVIEN(HOTEN, NS ,GT)
	VALUES(@HOTEN, @NS, @GT)
END
GO
--TẠO PROC SỬA:
CREATE PROC USP_UPDATENV
    @MANV INT,
	@HOTEN NVARCHAR(40),
	@NS DATE,
	@GT NVARCHAR(4)
AS
BEGIN 
	UPDATE NHANVIEN
	SET MANV = @MANV, HOTEN = @HOTEN, NS =@NS, GT =@GT
	WHERE MANV = @MANV
END
GO
--TẠO PROC XOÁ
CREATE PROC USP_DELETENV
	@MANV INT
AS
BEGIN
	DELETE NHANVIEN 
	WHERE MANV = @MANV
END
GO

--TẠO PROC TÌM KIẾM
CREATE PROCEDURE USP_SEARCHNV
	@SEARCHVALUE NVARCHAR(50)
AS
BEGIN
	SELECT MANV,HOTEN,NS,GT
	FROM NHANVIEN 
	WHERE (MANV LIKE N'%' + @SEARCHVALUE + '%') 
		OR (HOTEN LIKE N'%' + @SEARCHVALUE + '%') 
		OR (NS LIKE N'%' + @SEARCHVALUE + '%') 	
	   OR (GT LIKE N'%' + @SEARCHVALUE + '%') 	
END
GO
INSERT INTO NHANVIEN(HOTEN , NS , GT)
VALUES(N'Nguyễn Phạm Bảo Hân','19980816',N'Nữ')
GO
INSERT INTO NHANVIEN(HOTEN , NS , GT)
VALUES(N'Phạm Thị Thu Diễm','19980605',N'Nữ')
GO
SELECT * from NHANVIEN


----Mượn Sách----
CREATE PROC USP_GETMS
AS 
begin
SELECT MAMUON,MANV,MANM,MASACH,THOIGIAN,DATRAHAYCHUA
FROM MUONSACH
END
Go

--TẠO PROC THÊM
CREATE PROC USP_INSERTMS
	@MANV INT,
	@MANM INT,
	@MASACH INT,
	@THOIGIAN DATE,
	@DATRAHAYCHUA NVARCHAR(30)
AS
BEGIN
	INSERT INTO MUONSACH(MANV,MANM,MASACH,THOIGIAN,DATRAHAYCHUA)
	VALUES(@MANV, @MANM, @MASACH,@THOIGIAN,@DATRAHAYCHUA)
END
GO
--TẠO PROC SỬA:
CREATE PROC USP_UPDATEMS
   @MAMUON INT,
   @MANV INT,
	@MANM INT,
	@MASACH INT,
	@THOIGIAN DATE,
	@DATRAHAYCHUA NVARCHAR(30)
AS
BEGIN 
	UPDATE MUONSACH
	SET MANV = @MANV, MANM = @MANM, MASACH =@MASACH, THOIGIAN = @THOIGIAN, DATRAHAYCHUA = @DATRAHAYCHUA
	WHERE MAMUON = @MAMUON
END
GO
--TẠO PROC XOÁ
CREATE PROC USP_DELETEMS
	@MAMUON INT
AS
BEGIN
	DELETE MUONSACH 
	WHERE MAMUON = @MAMUON
END
GO

--TẠO PROC TÌM KIẾM
CREATE PROCEDURE USP_SEARCHMS
	@SEARCHVALUE NVARCHAR(50)
AS
BEGIN
	SELECT MAMUON,MANV,MANM,MASACH,THOIGIAN,DATRAHAYCHUA
	FROM MUONSACH 
	WHERE (MAMUON LIKE N'%' + @SEARCHVALUE + '%') 
		OR (MANV LIKE N'%' + @SEARCHVALUE + '%') 
		OR (MANM LIKE N'%' + @SEARCHVALUE + '%') 
		OR (MASACH LIKE N'%' + @SEARCHVALUE + '%') 	
	   OR (THOIGIAN LIKE N'%' + @SEARCHVALUE + '%')
	   OR (DATRAHAYCHUA LIKE N'%' + @SEARCHVALUE + '%')  	
END
GO

Insert into NGUOIMUON (HOTEN,NS,GT,DC,SDT)
values (N'Nguyen An','1998/11/02',N'Nữ',N'Hà Nội','012345678')
Go
Insert into NGUOIMUON (HOTEN,NS,GT,DC,SDT)
values (N'Phạm Trang','1998/12/01',N'Nữ',N'Hà Nội','0339876567')
Go
Insert into MUONSACH (MANV,MANM,MASACH,THOIGIAN,DATRAHAYCHUA)
values('5','1','2','2019/04/01',N'Đã Trả')
Insert into MUONSACH (MANV,MANM,MASACH,THOIGIAN,DATRAHAYCHUA)
values('8','2','10','2019/11/12',N'Chưa Trả')
Select * from MUONSACH

------------------Tác giả---------------------------
-- 1. GetAll
create procedure SP_TacGia_GetAll
as
begin
	select * from TACGIA
end
go
-- 2. Insert
create procedure SP_TacGia_Insert 
	@tenTacGia nvarchar(50)
as
begin
	insert into TACGIA(TENTG)
	values(@tenTacGia)
end
go
-- 3. Delete
create procedure SP_TacGia_Delete
	@maTacGia int
as
begin
	delete TACGIA
	where MATG = @maTacGia
end
go
-- 4. Update 
create procedure SP_TacGia_Update
	@maTacGia int, @tenTacGia nvarchar(50)
as
begin
	update TACGIA
	set TENTG = @tenTacGia
	where MATG = @maTacGia
end
go
-- 5. Search tac gia
create procedure SP_TacGia_Search
	@searchString nvarchar(100)
as
begin
	select * from TACGIA
	where TENTG like N'%'+@searchString+'%'
	or MATG like N'%'+@searchString+'%'
end
go
--------------------- Thể loại -------------------
-- 1. GetAll
create procedure SP_TheLoai_GetAll
as
begin
	select * from THELOAI
end
go
-- 2. Insert
create procedure SP_TheLoai_Insert
	@tenTheLoai nvarchar(50)
as
begin
	insert into THELOAI
	values(@tenTheLoai)
end
go
-- 3. delete
create procedure SP_TheLoai_Delete 
	@maTheLoai int
as
begin
	delete THELOAI
	where MATHELOAI = @maTheLoai
end
go

-- 4. Update
create procedure SP_TheLoai_Update
	@maTheLoai int, @tenTheLoai nvarchar(50)
as
begin
	update THELOAI
	set TENTHELOAI = @tenTheLoai
	where MATHELOAI = @maTheLoai
end
go

-- 5. Search
create procedure SP_TheLoai_Search
	@searchString nvarchar(100)
as
begin
	select * from THELOAI
	where MATHELOAI like N'%'+@searchString+'%'
	or TENTHELOAI like N'%'+@searchString+'%'
end
go
=======

--------------------------------------------------------NGUOI MUON--------------------------------------------------------------
GO
CREATE PROC USP_GetNguoiMuon
AS
SELECT * FROM dbo.NGUOIMUON
GO

INSERT dbo.NGUOIMUON
        ( HOTEN, NS, GT, DC, SDT )
VALUES  ( N'a', -- HOTEN - nvarchar(40)
          GETDATE(), -- NS - date
          N'Nữ', -- GT - nvarchar(4)
          N'122', -- DC - nvarchar(100)
          N'12132'  -- SDT - nchar(15)
          )
GO
CREATE PROC USP_InsertNguoiMuon
@hoten NVARCHAR(40),
@ngaysinh DATE,
@gioitinh NVARCHAR(4),
@diachi NVARCHAR(100),
@sdt VARCHAR(11)
AS
BEGIN
	INSERT dbo.NGUOIMUON
	        ( HOTEN, NS, GT, DC, SDT )
	VALUES  ( @hoten, -- HOTEN - nvarchar(40)
	          @ngaysinh, -- NS - date
	          @gioitinh, -- GT - nvarchar(4)
	          @diachi, -- DC - nvarchar(100)
	          @sdt  -- SDT - nchar(15)
	          )
END
GO
CREATE PROC USP_UpdateNguoiMuon
@manm INT,
@hoten NVARCHAR(40),
@ngaysinh DATE,
@gioitinh NVARCHAR(4),
@diachi NVARCHAR(100),
@sdt VARCHAR(11)
AS
BEGIN
	UPDATE dbo.NGUOIMUON SET HOTEN=@hoten,NS=@ngaysinh,GT=@gioitinh,DC=@diachi,SDT=@sdt WHERE MANM=@manm
END
GO
CREATE PROC USP_DeleteNguoiMuon
@manm INT
AS
BEGIN
	DELETE FROM dbo.NGUOIMUON WHERE MANM=@manm
END
GO
CREATE PROC USP_SearchNguoiMuon
@search NVARCHAR(100)
AS
BEGIN
	SELECT * FROM dbo.NGUOIMUON WHERE MANM LIKE N'%'+@search+'%' OR HOTEN LIKE N'%'+@search+'%' OR 
									  NS LIKE N'%'+@search+'%' OR GT LIKE N'%'+@search+'%' OR 
									  DC LIKE N'%'+@search+'%' OR SDT LIKE N'%'+@search+'%'
END
>>>>>>> NguyenHau
