CREATE DATABASE TT_QLTV
USE TT_QLTV
GO
CREATE TABLE SACH (
     MASACH INT IDENTITY(1,1) NOT NULL,
	TENSACH NVARCHAR(50),
	 GIATRI NVARCHAR(20)
)
CREATE TABLE NHANVIEN (
    MANV INT IDENTITY(1,1) NOT NULL,
	HOTEN NVARCHAR(40),
	NS DATE,
	GT NVARCHAR(4)
)
CREATE TABLE NGUOIMUON(
    MANM INT IDENTITY(1,1) NOT NULL,
	HOTEN NVARCHAR(40),
	NS DATE,
	GT NVARCHAR(4),
	DC NVARCHAR(100),
	SDT NCHAR(15)
	)
GO
CREATE TABLE MUONSACH(
   MAMUON INT IDENTITY(1,1) NOT NULL,
   MANV INT,
   MANM INT,
   MASACH INT,
   THOIGIAN DATE,
   DATRAHAYCHUA NVARCHAR(30)
   )
GO
 
CREATE TABLE THELOAI(
   MATHELOAI INT IDENTITY(1,1) NOT NULL,
   TENTHELOAI NVARCHAR(100)
   )
GO
CREATE TABLE TACGIA(
   MATG INT IDENTITY(1,1) NOT NULL,
   TENTG NVARCHAR(40)
   )
GO
CREATE TABLE PHANLOAI(
   MAPL INT IDENTITY(1,1) NOT NULL,
   MASACH INT,
   MATHELOAI INT
   )
GO
CREATE TABLE SANGTAC(
   MASANGTAC INT IDENTITY(1,1) NOT NULL,
   MATG INT,
   MASACH INT
   )
GO
ALTER TABLE dbo.SACH ADD CONSTRAINT PK_MASACH  PRIMARY KEY(MASACH)
ALTER TABLE dbo.NHANVIEN ADD CONSTRAINT PK_MANV  PRIMARY KEY(MANV)
ALTER TABLE dbo.NGUOIMUON ADD CONSTRAINT PK_MANM  PRIMARY KEY(MANM)
ALTER TABLE dbo.MUONSACH ADD CONSTRAINT PK_MAMUON  PRIMARY KEY(MAMUON)
ALTER TABLE dbo.THELOAI ADD CONSTRAINT PK_MATHELOAI  PRIMARY KEY(MATHELOAI)
ALTER TABLE dbo.TACGIA ADD CONSTRAINT PK_MATG  PRIMARY KEY(MATG)
ALTER TABLE dbo.SANGTAC ADD CONSTRAINT PK_MASANGTAC  PRIMARY KEY(MASANGTAC) 
ALTER TABLE dbo.PHANLOAI ADD CONSTRAINT PK_MAPL  PRIMARY KEY(MAPL)
ALTER TABLE dbo.SANGTAC ADD CONSTRAINT FK_MASACH_ST_SA FOREIGN KEY(MASACH) REFERENCES dbo.SACH(MASACH)
ALTER TABLE dbo.SANGTAC ADD CONSTRAINT FK_MATG_ST_TG FOREIGN KEY(MATG) REFERENCES dbo.TACGIA(MATG)
ALTER TABLE dbo.PHANLOAI ADD CONSTRAINT FK_MASACH_PL_SA FOREIGN KEY(MASACH) REFERENCES dbo.SACH(MASACH)
ALTER TABLE dbo.PHANLOAI ADD CONSTRAINT FK_MATHELOAI_PL_TL FOREIGN KEY(MATHELOAI) REFERENCES dbo.THELOAI(MATHELOAI)
ALTER TABLE dbo.MUONSACH ADD CONSTRAINT FK_MASACH_MS_SA FOREIGN KEY(MASACH) REFERENCES dbo.SACH(MASACH)
ALTER TABLE dbo.MUONSACH ADD CONSTRAINT FK_MANV_MS_NV FOREIGN KEY(MANV) REFERENCES dbo.NHANVIEN(MANV)
ALTER TABLE dbo.MUONSACH ADD CONSTRAINT FK_MANM_MS_NM FOREIGN KEY(MANM) REFERENCES dbo.NGUOIMUON(MANM)

GO
------------SÁCH-----------
INSERT INTO SACH(TENSACH , GIATRI)
VALUES(N'Để trở thành code điên','120000')
GO
INSERT INTO SACH(TENSACH , GIATRI)
VALUES(N'Mười vạn câu hỏi vì sao','300000')
GO

create PROC USP_GETSACH 
AS 
begin
SELECT MASACH,TENSACH,GIATRI
FROM SACH
end
exec USP_GETSACH
GO
--TẠO PROC THÊM
CREATE PROC USP_INSERTSACH
	@TENSACH NVARCHAR(50),
	@GIATRI NVARCHAR(20)
AS
BEGIN
	INSERT INTO SACH(TENSACH, GIATRI)
	VALUES(@TENSACH, @GIATRI)
END
GO
 
--TẠO PROC SỬA:
CREATE PROC USP_UPDATESACH
	@MASACH INT,
	@TENSACH NVARCHAR(50),
	@GIATRI NVARCHAR(20)
AS
BEGIN 
	UPDATE SACH
	SET TENSACH = @TENSACH, GIATRI = @GIATRI
	WHERE MASACH = @MASACH
END
GO

--TẠO PROC XOÁ
CREATE PROC USP_DELETESACH
	@MASACH INT
AS
BEGIN
	DELETE SACH 
	WHERE MASACH = @MASACH
END
GO

--TẠO PROC TÌM KIẾM
CREATE PROCEDURE USP_SEARCHSACH
	@SEARCHVALUE NVARCHAR(50)
AS
BEGIN
	SELECT MASACH,TENSACH,GIATRI
	FROM SACH 
	WHERE (MASACH LIKE N'%' + @SEARCHVALUE + '%') 
		OR (TENSACH LIKE N'%' + @SEARCHVALUE + '%') 
		OR (GIATRI LIKE N'%' + @SEARCHVALUE + '%') 	
END
GO

    -------------------------------------SANG TAC-----------------------
	---GETALL---
	CREATE PROC USP_SANGTAC_GETDSST
	AS
	    SELECT *FROM SANGTAC
	GO

	 ---INSERT----------------
	 CREATE PROC USP_SANGTAC_INSERT
	            @maTG int,
				@maSach int
	 AS
	 BEGIN
	    INSERT [dbo].[SANGTAC]( MATG, MASACH)
		VALUES (@maTG,@maSach)
	 END
	 GO


	 ------UPDATE-----------------
	 CREATE PROC USP_SANGTAC_UPDATE
	       @maST int,
		   @maTG int,
		   @maSach int
	AS
	BEGIN
	 UPDATE [dbo].[SANGTAC]
	 SET MATG = @maTG ,MASACH = @maSach
	 WHERE MASANGTAC = @maST
	END
	GO

	----------------DELETE------------------
	CREATE PROC USP_SANGTAC_DELETE
	     @maST INT

	AS
	BEGIN
	   DELETE [dbo].[SANGTAC]
	   WHERE MASANGTAC = @maST
	END
	GO

	------------SEARCH--------------------
	CREATE PROC USP_SANGTAC_SEARCH
	    @SEARCH NVARCHAR(100)
	AS
	BEGIN
	   SELECT MASANGTAC, MATG, MASACH
		FROM [dbo].[SANGTAC]
		WHERE (MASANGTAC LIKE N'%' + @SEARCH +'%')
		OR (MATG LIKE N'%' + @SEARCH + '%')
		OR (MASACH LIKE N'%' + @SEARCH + '%')
	END
	GO


	
	 INSERT [dbo].[TACGIA]( TENTG)
	 VALUES (N'Nguyễn Văn A')
	 INSERT [dbo].[TACGIA]( TENTG)
	 VALUES (N'Hoàng Văn X')
	 GO


	 [dbo].[USP_INSERTSACH] N'Giáo Dục Thể Chất', '100000'
	 GO
	 [dbo].[USP_INSERTSACH] N'Giải Tích 1', '200000'
	 GO
	 SELECT *FROM [dbo].[TACGIA]
	 SELECT *FROM [dbo].[SACH]
	 select *from [dbo].[SANGTAC]